"""Builds the design language's one font file and its @font-face sheet from the pinned sources.

    python3 -m venv .venv && .venv/bin/pip install -r scripts/requirements.txt
    .venv/bin/python scripts/build-font.py

Sources, in fonts/source/:
    Archivo[wdth,wght].ttf  google/fonts@6c70c829f09ea345d3590406693220ea35c6553f, ofl/archivo
                            sha256 0e094a7d3c7c4c25cf1310c4b30014f1dae9332220b1c2c88f4fa996f0b05053
    OFL.txt                 the same commit's licence
    GF_Latin_Core.nam       googlefonts/glyphsets@87be2b9c86227f277811e2fb40f1415652f5d977,
                            data/results/nam/GF_Latin_Core.nam
                            sha256 26936a4812ff33ee62a2e8156b9976173755909be84138ca4794a33f123b7d18
"""

import hashlib
from pathlib import Path

from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "fonts" / "source" / "Archivo[wdth,wght].ttf"
SOURCE_SHA256 = "0e094a7d3c7c4c25cf1310c4b30014f1dae9332220b1c2c88f4fa996f0b05053"
GLYPH_SET = ROOT / "fonts" / "source" / "GF_Latin_Core.nam"
GLYPH_SET_SHA256 = "26936a4812ff33ee62a2e8156b9976173755909be84138ca4794a33f123b7d18"
OUT_FONT = ROOT / "src" / "font" / "archivo.woff2"
OUT_CSS = ROOT / "src" / "font" / "archivo.css"

# The axes the language uses: the body cut's 400 and 100%, the display cut's 700 and 75%.
AXES = {"wght": (400, 700), "wdth": (75, 100)}
BODY_CUT = {"wght": 400, "wdth": 100}

# Kerning and mark positioning, glyph composition and localized forms, tabular numerals; and rvrn,
# which swaps the currency signs' heavier drawings in from weight 500 up.
FEATURES = ["kern", "mark", "mkmk", "ccmp", "locl", "tnum", "rvrn"]

# English letter frequencies (with the word space), weighting the average advance a line of running
# text is made of.
FREQUENCIES = {
    "e": 12.70, "t": 9.06, "a": 8.17, "o": 7.51, "i": 6.97, "n": 6.75, "s": 6.33, "h": 6.09,
    "r": 5.99, "d": 4.25, "l": 4.03, "c": 2.78, "u": 2.76, "m": 2.41, "w": 2.36, "f": 2.23,
    "g": 2.02, "y": 1.97, "p": 1.93, "b": 1.29, "v": 0.98, "k": 0.77, "j": 0.15, "x": 0.15,
    "q": 0.095, "z": 0.074, " ": 18.0,
}

# Arial 5.01's average advance by the same weighting, in em, measured from its hmtx table. Arial is
# the system sans the fallback face draws on; Liberation Sans shares its advances.
ARIAL_AVERAGE_ADVANCE = 0.44678


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def codepoints(path: Path) -> list:
    return [int(line.split()[0], 16) for line in path.read_text().splitlines() if line.startswith("0x")]


# Metrics at a location are read unrounded, as a renderer interpolates them.
def average_advance(font: TTFont, location: dict) -> float:
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet(location=location)
    total = sum(FREQUENCIES.values())
    weighted = sum(glyphs[cmap[ord(char)]].width * weight for char, weight in FREQUENCIES.items())
    return weighted / total / font["head"].unitsPerEm


def x_height(font: TTFont, location: dict) -> float:
    glyphs = font.getGlyphSet(location=location)
    pen = BoundsPen(glyphs)
    glyphs[font.getBestCmap()[ord("x")]].draw(pen)
    return pen.bounds[3] / font["head"].unitsPerEm


def percent(value: float) -> str:
    return f"{round(value * 100, 2):g}%"


def main() -> None:
    assert sha256(SOURCE) == SOURCE_SHA256, "the Archivo source is not the pinned file"
    assert sha256(GLYPH_SET) == GLYPH_SET_SHA256, "the glyph set is not the pinned file"

    font = instancer.instantiateVariableFont(TTFont(SOURCE), AXES)

    options = subset.Options()
    options.layout_features = FEATURES
    options.flavor = "woff2"
    options.notdef_outline = True
    # Every name record stays, the typographic family "Archivo" among them.
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=codepoints(GLYPH_SET))
    subsetter.subset(font)
    OUT_FONT.parent.mkdir(parents=True, exist_ok=True)
    font.flavor = "woff2"
    # The source's own timestamp stays, so the same sources build the same bytes.
    font.recalcTimestamp = False
    font.save(OUT_FONT)

    # The fallback is matched to the body cut, the cut running text is set in.
    built = TTFont(OUT_FONT)
    upm = built["head"].unitsPerEm
    size_adjust = average_advance(built, BODY_CUT) / ARIAL_AVERAGE_ADVANCE
    ascent = built["hhea"].ascent / upm
    descent = -built["hhea"].descent / upm
    line_gap = built["hhea"].lineGap / upm

    OUT_CSS.write_text(
        f"""/* Generated by scripts/build-font.py from Archivo (SIL Open Font License 1.1, fonts/source/OFL.txt). */

/* One variable file: weight 400–700, width 75–100%, GF Latin Core. */
@font-face {{
  font-family: 'Archivo';
  font-style: normal;
  font-weight: 400 700;
  font-stretch: 75% 100%;
  font-display: swap;
  src: url('./archivo.woff2') format('woff2');
}}

/* Arial scaled to the body cut's average advance ({percent(size_adjust)}), with Archivo's own
   ascent, descent and line gap, so the swap to the web font does not reflow a line. */
@font-face {{
  font-family: 'Archivo Fallback';
  src: local('Arial'), local('ArialMT'), local('Liberation Sans');
  size-adjust: {percent(size_adjust)};
  ascent-override: {percent(ascent / size_adjust)};
  descent-override: {percent(descent / size_adjust)};
  line-gap-override: {percent(line_gap / size_adjust)};
}}
"""
    )

    print(f"{OUT_FONT.relative_to(ROOT)}: {OUT_FONT.stat().st_size} bytes")
    print(f"x-height {x_height(built, BODY_CUT):.4f} em, size-adjust {percent(size_adjust)}")


if __name__ == "__main__":
    main()
